# Generated by Django 3.0.5 on 2020-10-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
