# Generated by Django 3.0.5 on 2020-10-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0002_auto_20201005_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
