# Generated by Django 3.0.5 on 2020-10-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0004_auto_20201005_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
