# Generated by Django 3.0.5 on 2020-10-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0006_auto_20201005_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
    ]
