# Generated by Django 3.0.5 on 2020-10-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0007_remove_project_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
