# Generated by Django 3.0.5 on 2020-10-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0008_delete_projectimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
