# Generated by Django 3.0.5 on 2020-10-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0010_auto_20201005_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
